// Fallback mock data — Instagram-themed component label distribution
const ALL_TICKETS = [
  { id: 'DS-101', name: 'Profile header redesign — backlog', labels: ['UXNotStarted'] },
  { id: 'DS-102', name: 'Feed carousel reaction affordances', labels: ['UXNotStarted'] },
  { id: 'DS-103', name: 'Explore topic chip layout', labels: ['UXNotStarted'] },
  { id: 'DS-104', name: 'Reels cover picker panel', labels: ['UXNotStarted'] },
  { id: 'DS-105', name: 'Subscription badge modal', labels: ['UXNotStarted'] },
  { id: 'DS-106', name: 'Creator analytics dashboard', labels: ['UXNotStarted'] },
  { id: 'DS-107', name: 'DM read receipts pattern', labels: ['UXNotStarted'] },
  { id: 'DS-108', name: 'Stories sticker tray exploration', labels: ['UXNotStarted'] },
  { id: 'DS-201', name: 'Feed card density refresh in progress', labels: ['UXInProgress'] },
  { id: 'DS-202', name: 'Activity center layout work', labels: ['UXInProgress'] },
  { id: 'DS-203', name: 'Profile highlights reordering', labels: ['UXInProgress'] },
  { id: 'DS-204', name: 'Mobile tab bar patterns', labels: ['UXInProgress'] },
  { id: 'DS-205', name: 'DM compose bar consolidation', labels: ['UXInProgress'] },
  { id: 'DS-206', name: 'Reels publish confirmation flow', labels: ['UXInProgress'] },
  { id: 'DS-301', name: 'Sign-up screen redesign — design complete', labels: ['UXDESIGNDONE'] },
  { id: 'DS-302', name: 'Profile photo crop finalized', labels: ['UXDESIGNDONE'] },
  { id: 'DS-303', name: 'Onboarding suggestions design complete', labels: ['UXDESIGNDONE'] },
  { id: 'DS-304', name: 'Feed empty state handoff done', labels: ['UXDESIGNDONE'] },
  { id: 'DS-305', name: 'Settings screens delivered', labels: ['UXDESIGNDONE'] },
  { id: 'DS-401', name: 'Explore search usability validation', labels: ['UXValidationinProgress'] },
  { id: 'DS-402', name: 'Profile edit flow validation', labels: ['UXValidationinProgress'] },
  { id: 'DS-403', name: 'DM voice message validation', labels: ['UXValidationinProgress'] },
  { id: 'DS-404', name: 'Collab post invite UX validation', labels: ['UXValidationinProgress'] },
  { id: 'DS-501', name: 'Creator badge treatment — design wrapping', labels: ['UXInProgress', 'UXDESIGNDONE'] },
  { id: 'DS-502', name: 'Reels comment threading — final screens', labels: ['UXInProgress', 'UXDESIGNDONE'] },
  { id: 'DS-503', name: 'Story reply bar preferences design', labels: ['UXInProgress', 'UXDESIGNDONE'] },
  { id: 'DS-601', name: 'Profile link-in-bio — validation', labels: ['UXDESIGNDONE', 'UXValidationinProgress'] },
  { id: 'DS-602', name: 'Spark AI captions validating', labels: ['UXDESIGNDONE', 'UXValidationinProgress'] },
  { id: 'DS-603', name: 'DM reactions in validation', labels: ['UXDESIGNDONE', 'UXValidationinProgress'] },
  { id: 'DS-604', name: 'Shop checkout flow validation', labels: ['UXDESIGNDONE', 'UXValidationinProgress'] },
  { id: 'DS-701', name: 'Creator support chat interface', labels: ['UXNotStarted', 'UXInProgress'] },
  { id: 'DS-702', name: 'Live broadcast discovery dashboard', labels: ['UXNotStarted', 'UXInProgress'] },
]